### ISSUE TITLE
Fix deadlinks detection

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#1059]
We currently check our docs for deadlinks:
https://github.com/Instagram/IGListKit/blob/master/.travis.yml#L48-L54

This is supposed to ignore `.vendor/` -- but it **is not**:
https://travis-ci.org/Instagram/IGListKit/jobs/331557269#L1293

**Comment by jessesquires** [comment]
@Sherlouk -- could you take a look at this?

(I think you set this up originally, right?)

**Comment by Sherlouk** [comment]
Looks like @rnystrom was the one who added the "not vendor" catch mine was super basic at first!

Looking at this SO post it looks like if we just drop the `.` it might fix the issue??
https://stackoverflow.com/a/15736463

Tad busy at the moment but if I get a chance I'll try and look into it, though the issue here appears to be simple shell stuff so anyone could pick this up without knowing the original work 😄

**Comment by jessesquires** [comment]
oh wait. i see the issue. we have `vendor`, it should be `.vendor`

**Comment by jessesquires** [comment]
putting up a PR
