### ISSUE TITLE
[Question] Will this continue to be supported? Why so long since the last release?

### ISSUE THREAD

**Issue by RamblinWreck77** [Instagram/IGListKit#1064]
Great project!

I'm concerned that the last release was in August 2017... has this project been abandoned? 

Currently it's full of warnings on Swift 4 / Xcode 9. I'd love to use it in my project, just want to make sure it's maintained going forward.

**Comment by viktorgardart** [comment]
I think this is the roadmap for the next release.
https://github.com/Instagram/IGListKit/milestone/6

**Comment by rnystrom** [comment]
Hey @RamblinWreck77! **Definitely** not abandoned. You can see the [commit history](https://github.com/Instagram/IGListKit/commits/master) is quite active.

You're right to call out that we haven't submitted a new release in a while. There's an internal change that is close to being merged right now, but we should cut a release _before_ that change since the current version is very stable.

I've been getting pretty burned out & distracted [battling](https://github.com/Instagram/IGListKit/pull/1025) Travis CI to just make our badge green. I'd hate to submit a new release showing "Build: Failing"...

I'm going to make an effort this week to cut 3.2 as the current stable, then merge our current PRs to get more soak time.

For reference though, Instagram continues to use and ship IGListKit from `master` every week. The project is actively used and extremely stable. We just don't have a huge need to change it much!

**Comment by RamblinWreck77** [comment]
@rnystrom Awesome! Thanks for the quick reply!
