### ISSUE TITLE
IGListKit how to support waterfall？

### ISSUE THREAD

**Issue by lingdachao** [Instagram/IGListKit#1106]
as title

**Comment by rnystrom** [comment]
Sorry we need a lot more detail before can be of any use.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Maybe you're talking about the common waterfall style collection view layout?

https://github.com/chiahsien/CHTCollectionViewWaterfallLayout (for example)

If so there's another discussion on the matter at #877 - Otherwise, as Ryan said, please give a little bit more information so we can help you better :)
