### ISSUE TITLE
About UICollectionView dequeueReusableCellWithReuseIdentifier

### ISSUE THREAD

**Issue by devcxm** [Instagram/IGListKit#1176]
When `MyCollectionViewCell` has two different cell reuseIdentifier, IGListKit unable to auto register  two different cell reuseIdentifier cell class.
```objective-c
- (__kindof UICollectionViewCell *)dequeueReusableCellOfClass:(Class)cellClass
                                 withReuseIdentifier:(NSString *)reuseIdentifier
                                forSectionController:(IGListSectionController *)sectionController
                                             atIndex:(NSInteger)index {
   ......

     // One cell class only cloud be registered once
    if (![self.registeredCellClasses containsObject:cellClass]) {
        [self.registeredCellClasses addObject:cellClass];
        [collectionView registerClass:cellClass forCellWithReuseIdentifier:identifier];
    }


    return [collectionView dequeueReusableCellWithReuseIdentifier:identifier forIndexPath:indexPath];
}
```

How to solve this problem? (sorry for my bad english.)

**Comment by rnystrom** [comment]
@devcxm if you use the latest version of IGListKit, you’ll notice that there is a new dequeue method with a `reuseIdentifier` parameter that will allow you to do just that!

Does that answer your question?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by devcxm** [comment]
I know that method, but the implementation of that method is the issues codes.
```Objective-C
// One cell class only cloud be registered once
    if (![self.registeredCellClasses containsObject:cellClass]) {
        [self.registeredCellClasses addObject:cellClass];
        [collectionView registerClass:cellClass forCellWithReuseIdentifier:identifier];
    }
```

**Comment by chandratjioe** [comment]
I think I know the problem here.
in that method, you set `identifier` with combination of `reuseIdentifier` and `cellClass`
```objc
    NSString *identifier = IGListReusableViewIdentifier(cellClass, nil, nil, reuseIdentifier);
```

but, `registeredCellClasses` store `cellClass` as unique key, not considering `reuseIdentifier`.
```objc
    if (![self.registeredCellClasses containsObject:cellClass]) {
```

For example, I want to register a class (let say `ClassX`) with two different reuse identifiers (`id1` and `id2`). Class `ClassX` is registered successfully with first identifier (`id1ClassX`). But for second identifier (`id2ClassX`), it will be crash since `registeredCellClasses` already contains `ClassX` and try to reuse with second identifier, but none exist for that identifier.

**Comment by devcxm** [comment]
I know the cause of the problem, and I fork to [https://gitee.com/cxmapp/IGListKit](https://gitee.com/cxmapp/IGListKit) and fix the problem.

**Comment by iperry90** [comment]
Closing this since the issue has been fixed.
