### ISSUE TITLE
Question: "Infinitely"-scrollable section with pagination

### ISSUE THREAD

**Issue by richardtop** [Instagram/IGListKit#1229]
I'm trying to achieve the following effect:
![screen shot 2018-07-27 at 20 46 41](https://user-images.githubusercontent.com/8013017/43338118-31801976-91de-11e8-8d43-791e19e7c96d.png)

**Q1:**
The layout consists of multiple sections. Each section consists of multiple cells, and the last section could be infinitely-scrollable (similar to the Instagram feed).

Instagram uses one "SectionController" per post, so the reloading the whole section is fast. In my case, it's not so easy, as the cells are grouped into larger sections. Later, section shadows and separators are added using the supplementary views.

Take for example, Section 2 - for now it consists only of 3 cells, but after loading finishes, it may have e.g. 500 cells.

IGListKit will perform the diff on the whole section, therefore iterating over those 500 cells and reloading the whole section, when essentially, it's a standard addition operation.

**Q2:**
Each section is loaded from a separate API endpoint, who should be responsible for the data loading in such case?
Initially, I planned that each SectionController would handle loading, but this seems not to play well with the IGListKit architecture. What is the common approach in such scenario?

**Comment by MussaCharles** [comment]
For Q1. I am doing almost the same thing on my app, what I do is for the infinite scrolling SectionController I use single section per post .Like on your image above I have the first few sectionControllers with more than one cell so I load the first sections and after that I return infinite scrolling SectionController with single section per post but it appear as if it is a section with multiple cells since I load it after the ones with multiple cells. Not sure if it is a best practice but currently this approach works for me. 

For Q2. My view Controller supply data to sectionControllers. It will be great If each section can handle data fetching, I am also waiting for responses on how to do it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
@MussaCharles thank you for your reply.

I picked the architecture described in [Advanced User Interfaces with Collection Views
](https://developer.apple.com/videos/play/wwdc2014/232/) video.
So, the DataSource (or "section controller", although it can control more than one section) is responsible for the data loading, therefore, removing the need to do any specific networking inside of a ViewController.

Regarding **Q1**, it seems that after adding new sections, your SectionController has to diff against the whole set of data instead of only a single append operation.

**Comment by MussaCharles** [comment]
@richardtop Great! I will have a look at that. About Q1 yeah you are right. I will try to find a better approach. Were you able to do network logics in each section separately?
