### ISSUE TITLE
IGListCollectionViewLayout partial optimization issue in certain situation 

### ISSUE THREAD

**Issue by qhhonx** [Instagram/IGListKit#1275]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): iOS12.1
- CocoaPods/Carthage version: 1.4.0
- Xcode version: 10.1
- Devices/Simulators affected: Both
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: No

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

### Description

If we use IGListBindingSectionController, and want to update first item of the section that both UI elements and cell size will be changed. Since IGListBindingSectionController can just `reload` cell not insert+delete, the updating cell will be invoked `bindViewModel:` again so that we can update its UI elements. However, we have no way to update the size of cell if using IGListCollectionViewLayout because of `minimumInvalidatedSection` not affected. And the `performBatchUpdates:` is not triggered by `updateAnimated:` in IGListBindingSectionController but `performUpdatesAnimated:` in IGListAdapter.

Below are related code snippets.

in IGListBindingSectionController.m
![image](https://user-images.githubusercontent.com/2561942/47985489-ae9e3700-e114-11e8-9903-5108bd83f765.png)
in IGListCollectionViewLayout.mm
![image](https://user-images.githubusercontent.com/2561942/47985561-f7ee8680-e114-11e8-87ef-a1b6e8f50020.png)

**Comment by rnystrom** [comment]
@xohozu is there a way to repro this in an example project so we can take a look?

Also you should be able to get around this by invalidating the layout on the collection context:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L236-L247

**Comment by xohozu** [comment]
[ModelingAndBinding.zip](https://github.com/Instagram/IGListKit/files/2618531/ModelingAndBinding.zip)

I uploaded a reproducible example project by reusing existing ModelingAndBinding demo.
In that project, some little changes as below:
- Dynamic height for ActionCell according to its likes count. 
```Swift
// in `PostSectionController.swift` line48
case let viewModel as ActionViewModel: height = CGFloat(55 + 2 * (viewModel.likes / 10))
```
- Use builtin IGListCollectionViewLayout by changing collectionView in `Main.storyboard` Layout to `Custom` and Class to `IGListCollectionViewLayout`.  

Some observed results as follow:
- When I tapped the heart icon, the numbers of likes updated and the size of ActionCell changed by using UICollectionViewFlowLayout.
- However, if using IGListCollectionViewLayout, When I tapped the heart icon, the numbers of likes updated because of `bindViewModel:` called, but the size of ActionCell not affected because of 
```Objective-C
// in `IGListCollectionViewLayout.mm` line447

- (void)_calculateLayoutIfNeeded {
    if (_minimumInvalidatedSection == NSNotFound) {
        return;
    }
    ...
}
```
always return in advance due to optimization of `IGListCollectionViewLayout`.

- Calling `invalidateLayoutForSectionController:completion:` before or in `updateAnimated:completion:`, all cells in that section will be re-calculate their sizes ignoring diffing results which mean only few cells should be re-calculate their sizes.

I have a straightforward solution to fix this issue probably that those updating(not inserts or deletes) cells need to invalidate their attributes before re-binding new view model in `updateAnimated:completion`.
