### ISSUE TITLE
Implement feed with groups of embedded section controllers

### ISSUE THREAD

**Issue by simonlee2** [Instagram/IGListKit#1311]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): 12.1
- CocoaPods/Carthage version: 1.5.3
- Xcode version: 10.1
- Devices/Simulators affected: all
- Reproducible in the demo project? (Yes/No): No
- Related issues: #1209

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

## Context

I'm implementing a feed where each `FeedItem` could have any number of horizontally scrollable rows. `FeedItem` looks something like this:

```swift
class FeedItem {
  let pk: Int
  let rows: [ListDiffable]
}

class ImageListRow: Row {
  let images: [UIImage]
}

class TextRow: ListDiffable {
    let pk: Int
    let text: String
}
```

The top level data then looks something like this:

```swift
[
  FeedItem(pk: 0, rows: [
    TextRow(pk: 0, text: "Foo"),
    ImageListRow(pk: 1, images: [UIImage(named: "image1")!,
                                 UIImage(named: "image2")!])
    ]),
  FeedItem(pk: 1, rows: [
    TextRow(pk: 2, text: "Bar"),
    ImageListRow(pk: 3, images: [UIImage(named: "image1")!,
                                 UIImage(named: "image2")!,
                                 UIImage(named: "image3")!]),
    ImageListRow(pk: 4, images: [UIImage(named: "image1")!,
                                 UIImage(named: "image2")!,
                                 UIImage(named: "image3")!,
                                 UIImage(named: "image4")!]),
    ])
]
```

Following the [example code](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/NestedAdapterViewController.swift), I flattened the list of `FeedItem`s into a list of `ListDiffable`, and implemented a section controller for each `TextRow` and `ImageListRow`. 

```swift
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
    return data.flatMap({ $0.rows })
}

func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
    switch object {
    case is TextRow:
        return TextSectionController()
    case is ImageListRow:
        return ImageListSectionController()
    default:
        return ListSectionController()
    }
}
```

As a result, the each row is its own section. The nested section controller works perfectly, and I was able to achieve something like the following:

<img src="https://raw.githubusercontent.com/simonlee2/FeedExample/master/Resources/screenshot.png" width="300">

## Question

I would like to add spacing between each `FeedItem`, so that it would look like this:

<img src="https://raw.githubusercontent.com/simonlee2/FeedExample/master/Resources/screenshot-edited.png" width="300">

I've considered several approaches:

1. I can't always set `ImageListSectionController`'s `inset.bottom` because it's not necessarily the last row of a `FeedItem`

2. While flattening the data to a list of rows, add some information to the last row, so the section controller for that row can add spacing at the bottom by setting its `inset`

    This could work, but I'm not sure if this is the best I can do. 

3. Use `IGListStackedSectionController` to wrap the section controllers for each row, then set the inset on the stacked section controller. 

    This could also work, but `IGListStackedSectionController` will be deprecated soon.

4. Use `IGListBindingSectionController`, which gets a `FeedItem`, then render each row as cells in each `FeedItem` section.

    Given that `FeedItem` is a logical group for individual rows, using `IGListBindingSectionController` makes the most sense to me. However, I'm stuck when implementing nested section controllers. I've looked at #1209, but I believe that approach would fail when there are more than one embedded cell within the section because the one `ListAdapter` in the section controller can't be bound to two different collection views at the same time.

Do you have any recommendations or tips on implementing something like this? Thanks!

## References

Here's my example project: https://github.com/simonlee2/FeedExample

**Comment by Smiller193** [comment]
good luck getting a quick answer. They seem to be pretty busy at the moment.

**Comment by Smiller193** [comment]
hey could I ask you for some help by any chance?

**Comment by simonlee2** [comment]
@Smiller193 sure!

**Comment by Smiller193** [comment]
@simonlee2 I couldn't get the proper number of section controller to show up
In my app I list events and there should be a section for each category but maybe only the first two pop up

**Comment by choujar** [comment]
@simonlee2 - I actually have a question for you actually, I'm trying a similar thing, but when I scroll one horizontal carousel, I find that other horizontal carousels (that are not on the screen) also end up scrolling... are you experiencing this behaviour? If not, I wonder what it is you've done differently because our setup looks very similar.

**Comment by DimaVartanian** [comment]
There's a bunch of ways to accomplish the padding you want. A couple come to mind:

1. Using the architecture you already have, you can simply add another row type to represent a spacer or padding. When constructing your model, just add one of these in between each other set of rows. It can then have its own section controller and cell which just adds some space.
2. Use a single section controller for each item instead of several. Each section controller would then contain several cells (your text cell and then your image list cell). Doing it this way, you can use the `inset` property on the section controller since it actually represents an individual model section now.
2. Another way is to divide this up would be with a nested collection view. Your top level level collection view would consist of a single section controller and cell per model, which in this case would be each feed item. Then, the cell for each of these sections would contain another collection view, which would each have the individual cells and sections you have now. As in the previous method, you can now use the `inset` property on the top level section controllers since they each represent one model item.

**Comment by DimaVartanian** [comment]
@choujar as for your question about scroll offsets, that is most likely because the horizontally scrollable cells you have are being reused as you scroll vertically, and their offsets are not fixed. To fix this, you'd want to either always reset the `contentOffset` of each embedded carousel to `0` before it is about to display, or save the offset per model when one ends displaying, and use that to set it when it's about to display again (if you want to save your place for each one).

**Comment by DimaVartanian** [comment]
Feel free to reopen this if there's a follow up question!

**Comment by SolorzanoJose** [comment]
> @simonlee2 I couldn't get the proper number of section controller to show up
> In my app I list events and there should be a section for each category but maybe only the first two pop up

For me, a nested list controller only shows the 1st item of the data source and not all
