### ISSUE TITLE
 Does this framework support pre load cell?

### ISSUE THREAD

**Issue by karosLi** [Instagram/IGListKit#1329]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

 ## Does this framework support pre load cell?
Example:  I have several sections and each section has different kind of cell. Then fourth section is at out of screen, when i scroll to this section, UIKit will dynamic create cell in this section, but at this time, the CPU will increase to 200%, and the scroll will stuck. So in this case, i want to pre load cell in four section, does this framework support pre load cell?

**Comment by Ziewvater** [comment]
It sounds to me like your issue lies less with the ability to pre-load a cell, and more that you're performing too much work on the main thread when you're creating a new cell. I'd look into what's causing your CPU usage to jump at this time (try Instruments), and try to perform that work elsewhere, perhaps asynchronously on a background thread.
