### ISSUE TITLE
Vertical pagination causes feed to jump position

### ISSUE THREAD

**Issue by t3ddyK** [Instagram/IGListKit#1332]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): 12
- CocoaPods/Carthage version: 3.4.0
- Xcode version: 10.2
- Devices/Simulators affected: XS
- Reproducible in the demo project?: Yes
- Related issues:

I am trying to implement infinite scrolling w/ `IGListKit`. I have followed the example code, however this is a simple text cell with a fixed height.

**I am using self sizing cells that render images.**

My images are cached using `Kingfisher`. I would expect to scroll view to maintain its position and append any new items below, essentially increasing the scrollable area.

Instead what is happening is my feed jumps back to the first item after adding the new items.

I have mocked the latency of a network call in my `scrollViewWillEndDragging` method, appending new items to the end of the collection and calling `adapter.performUpdates(animated: false)` when the collection `didSet` is triggered.

[IGListKitDemo.zip](https://github.com/Instagram/IGListKit/files/3335276/IGListKitDemo.zip)

**Comment by DimaVartanian** [comment]
One curious thing I noticed is that the jump to top only seems to happen if your target offset when dragging is past the bottom of the content size. In other words, if you fling the scroll view just a bit, not enough that it will bounce, the jump does not occur. Not sure exactly why this is, though.
https://github.com/Instagram/IGListKit/issues/516

I think this is an issue with some combination of the collection view layout and cell sizing code, but I'm not sure exactly what it is.

I was able to pretty much completely fix this by modifying your `sizeForItem(at:)` method in `ImageSectionController` to simply return `image.heightForFeed` instead of `1` for the height. It's possible the estimate size being 10 could also be an issue. Since the fix was relatively simple, I hope that it solves your issue.

Feel free to reopen this if you have a follow up question.
