### ISSUE TITLE
Make animation inside cell

### ISSUE THREAD

**Issue by trieuhellodenteam** [Instagram/IGListKit#1333]
## New issue checklist

- [x ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x ] I have attempted to reproduce the issue and include an example project.

### General information

My app need to blink a UIView inside each cell. I used this code for UITableViewCell but it doesn't work inside IGList (Animations will stop when scrolling). Have you any suggestions for me 
```    
override func cellForItem(at index: Int) -> UICollectionViewCell {
        guard let cell = collectionContext?.dequeueReusableCellFromStoryboard(withIdentifier: "OrderInfoLaterCell", for: self, at: index) as? OrderInfoLaterCell else {
            fatalError()
        }
        cell.order = order
        DispatchQueue.main.async { [weak self] in
            if let this = self {
                if this.order.isAnimation() {
                    UIView.animate(withDuration: 1.0, delay: 0, options: [.repeat, .autoreverse], animations: {
                        cell.lblStatus.alpha = 0.2
                        }, completion: nil)
                } else {
                    cell.lblStatus.alpha = 1.0
                }
            }
        }
        return cell
    }
```

**Comment by DimaVartanian** [comment]
HI @trieuhellodenteam! So looking at this, it appears that it's most likely not really an IGListKit issue but more of a UICollectionView thing in general. At a glance it's probably not the best idea to try to start an animation in the `cellForItem()` method since the cell might not be totally set up yet, or on the screen. You'll most likely have better luck sticking the animation code in a spot closer to displaying the cell, in particular into `listAdapter(willDisplay:cell:at:)`

If you're still having trouble, please provide a sample project that illustrates the issue so we can better help.
