### ISSUE TITLE
Multiple sections per row with alternate sizing

### ISSUE THREAD

**Issue by t3ddyK** [Instagram/IGListKit#1378]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: latest
- iOS version(s): latest
- CocoaPods/Carthage version: latest
- Xcode version: latest
- Devices/Simulators affected: iPad
- Reproducible in the demo project? (Yes/No):
- Related issues:

I am trying to create a feed layout in this fashion

```
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
[---1/3---][-------2/3-------] /* 2 items - 1 third and 2 thirds */
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
[---1/3---][-------2/3-------] /* 2 items - 1 third and 2 thirds */
```

I was able to kind of achieve this by doing something like

```swift
class FeedSectionController: ListSectionController {
    
    var entry: FeedEntry!
    
    override init() {
        super.init()
        inset = UIEdgeInsets(top: 0, left: 0, bottom: 15, right: 0)
    }
    
    override func numberOfItems() -> Int {
        return 2
    }
    
    override func sizeForItem(at index: Int) -> CGSize {
        
        guard let ctx = collectionContext else { return .zero }
        
        if index == 0 {
            return CGSize(width: ((ctx.containerSize.width / 3) * 2), height: 30)
        } else {
            return CGSize(width: (ctx.containerSize.width / 3), height: 30)
        }
    }
    
    override func cellForItem(at index: Int) -> UICollectionViewCell {
        let cell = UICollectionViewCell()
        cell.backgroundColor = index % 2 == 0 ? .lightGray : .darkGray

        return cell
    }
    
    override func didUpdate(to object: Any) {
        entry = object as? FeedEntry
    }
}
```

However the result is really more like
```
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
[-------2/3-------][---1/3---] /* 2 items - 2 thirds and 1 third */
```
Which is not quite right, also it means I have 2 entire feed items per cell, per section.

What I'd like is each section to contain X amount of cells that essentially construct a single feed item.

```
[-------2/3-------][---1/3---] /* 2 sections - 2 thirds and 1 third */
[---1/3---][-------2/3-------] /* 2 sections - 1 third and 2 thirds */
[-------2/3-------][---1/3---] /* 2 sections - 2 thirds and 1 third */
[---1/3---][-------2/3-------] /* 2 sections - 1 third and 2 thirds */
```

To do this however I need to to layout `FeedSectionController` in the fashion outlined earlier, not the items within `FeedSectionController` (I think).

**Comment by nodediggity** [comment]
The reason you are seeing this design - 

```
[-------2/3-------][---1/3---] 
[-------2/3-------][---1/3---] 
[-------2/3-------][---1/3---] 
[-------2/3-------][---1/3---] 
```

Is essentially because of 2 things - 

```swift
override func numberOfItems() -> Int {
    return 2
}
```
and
```swift
if index == 0 {
    return CGSize(width: ((ctx.containerSize.width / 3) * 2), height: 30)
} else {
    return CGSize(width: (ctx.containerSize.width / 3), height: 30)
}
```

This pretty much ensures `index` will only ever be `0` or `1` and you will only ever 2 cells per section.

Take a look at the [HorizontalSectionController](https://github.com/Instagram/IGListKit/blob/8d8a632b679b0a684e17bec2b81171da62893a9b/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift#L22) from the example projects. This uses a [NestedAdapterViewController](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/NestedAdapterViewController.swift) which I believe is the pattern you will want to follow.

This way your initial section controller can specify the number of feed items using `numberOfItems` and you can manage the width of each item using `sizeForItem`. Then rather than returning your feed item directly, you can return a nested adapter that contains your feed item, with enough cells to satisfy the design requirements.

**Comment by iperry90** [comment]
Closing this since it looks like @nodediggity provided a good answer! @t3ddyK feel free to reopen if you have additional questions.
