### ISSUE TITLE
IGListSectionController background view API

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#142]
Random thought I had today working on a tutorial for IGListKit.

What if we had an API to give `IGListSectionController`s a `backgroundView` property sort of like `UICollectionView` has? This would make putting background/border views around a section pretty easy.

As for how it'd work, we could put the views in the `IGListCollectionView` itself and manage positions.

**Comment by rnystrom** [comment]
Also I'm open to hearing how to provide better section-border support natively too.

**Comment by ishabazz** [comment]
What's the current way to set the section background?

**Comment by rnystrom** [comment]
@ishabazz there isn't one 😄 

I'm not sure how valuable this would be, and it could be pretty complicated keeping up w/ `UICollectionView` changes, so this might not be worth it.

**Comment by zhubofei** [comment]
@rnystrom IMHO the standard way of adding backgrounds to `UICollectionView` is through Decoration View.

**Comment by varyP** [comment]
@rnystrom 
Any updates on this?
Problem : Wanting to divide a big cell into smaller chunks using a binding controller, but can't quite round corner & shadow'fy the UI. Consider multiple cells inside 1 rounded corner section with shadow.

Apologies if this has been discussed already, to describe the situation i'm in right now :
I tried using the decoration view, since it is a supplementary view behind the UICollectionCellView, my ASCellNode(using texture as well) is placed over the decoration view, since it is not a child of the decoration view, it doesn't get rounded off the corners, so it's like having a flat view placed over a rounded view, looks very weird.

Secondly, even the decoration view(by subclassing the UICollectionViewFlowLayout), seemed to be only wrapping each cell & not the whole section.
