### ISSUE TITLE
Xcode12 issue navigator warnings

### ISSUE THREAD

**Issue by arangato** [Instagram/IGListKit#1463]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- Xcode version: 12
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

Xcode 12 shows warnings in issue navigator and suggests to update IGListKit project to recommended settings, which include:
- raising deployment target to 12.0
- enabling quoted include in framework header warning

**Comment by joetam** [comment]
Unfortunately, if we applied these recommended settings on Xcode 12, it will break for the users on older Xcode versions, as well as for apps that don't wish to bump their minimum deployment target. Since the gain is minimal but hurts potential adopters of this framework, I don't think we will pursue this.

**Comment by arangato** [comment]
Thank you @joetam for explanation. Changing deployment target is indeed very intrusive. How about the other thing ?
I just tested applying "enabling quoted include in framework header warning". Issue navigator warning disappeared even without touching deployment target.
