### ISSUE TITLE
Tail loading data with dynamic cell size issue

### ISSUE THREAD

**Issue by twentyseven** [Instagram/IGListKit#266]
Hi, so what I'm trying to do is to combine the "tail loading" example with "self sizing cell" one to achieve a social feed page-like. I have updated the `SelfSizingCellController.swift` to include the dragging delegate of scroll view to let it able to calculate the distance and fake a load more with duplicated data (please look at the screenshot), but every time after finished loading and update the new data, the content offset of collection view was reset to some random point and somehow the scroll up or down become crazy. Thanks for any help guys!

<img width="1512" alt="screen shot 2016-11-28 at 5 36 56 pm" src="https://cloud.githubusercontent.com/assets/1741561/20665261/8138df5a-b591-11e6-8b98-07e60603fe35.png">

**Comment by rnystrom** [comment]
Hmm, this is honestly probably a limitation with self-sizing cells and `UICollectionView`. If you can provide a sample project we can poke around and try to find a solution, but I remember `UITableView` auto height cells having weird content offset issues too.

**Comment by twentyseven** [comment]
[Examples-iOS.zip](https://github.com/Instagram/IGListKit/files/617995/Examples-iOS.zip)
Sure, this is the sample project which I combined tail-loading and self-sizing. Previously I make this work by using `UITableView` along with autolayout constraints applied on cells and return the `UITableViewAutomaticDimension` for the cell height delegate, also added a cache of height t o resolve some jumpy scrolling: http://stackoverflow.com/questions/27996438/jerky-scrolling-after-updating-uitableviewcell-in-place-with-uitableviewautomati
I wonder how it works in Instagram with dynamic cell height and tail loading also.

**Comment by jamesrisberg** [comment]
Bump bump bump, running into this issue as well!

**Comment by rnystrom** [comment]
@jamesrisberg we've got other estimated size issues floating around (#452). It looks like there are some weird behaviors going on. Estimated size is dependent on `UICollectionViewFlowLayout` and I'm trying to avoid any layout-specific fixes. However if we can't find a common solution we might have to.

**Comment by jamesrisberg** [comment]
@rnystrom Yeah, the content offsets get real wonky and sections start overlapping each other. I've just moved to calculating the heights manually for now, which isn't the end of the world since I'm just sizing cells for single textViews and the calculation is pretty lightweight.

Definitely something to be fixed. Maybe abstracting the layout to take any layout (Flow or otherwise) and making a `UICollectionViewFlowLayout` behind the scenes, since everything you can accomplish with a standard layout object you should be able to accomplish with a flow layout, but not vice versa.

Gonna do a little digging when I have the time and see if that's a viable path to go down

**Comment by jessesquires** [comment]
Closing to track at #516
