### ISSUE TITLE
Bug when a section reload is queued while batch updating

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#288]
I discovered this working on my sample weather app. Here's the conditions that I noticed to reproduce this:

- Add a `Dispatch.async { ... }` inside `didUpdate(to object:)`
- In the block, call `collectionContext.reload(section: self)`
  - Note **do not** use batch updating

Result: reload will never be called. 

This is because `-[UICollectionView performBatchUpdates:completion:]`, is asynchronous in that it executes over several runloop turns (aggregation and animations).

We use a [flag](https://github.com/Instagram/IGListKit/blob/cdc796746adf95d9a9ae78379a29cddf50c9f738/Source/Internal/IGListAdapterUpdaterInternal.h#L44) to monitor when batch updating, setting it to [YES](https://github.com/Instagram/IGListKit/blob/8ea5e088809b6ea3fe0335d3fdd59f8c77301574/Source/IGListAdapterUpdater.m#L280-L281) _before_ we enter the update block, then setting it to [NO](https://github.com/Instagram/IGListKit/blob/8ea5e088809b6ea3fe0335d3fdd59f8c77301574/Source/IGListAdapterUpdater.m#L289) in the **completion block** of `performBatchUpdates:completion:`.

If a reload is added while this flag is set to `YES`, [we assume](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L481) it is part of unloading our blocks of batched operations.

The problem is anyone can queue a reload from anywhere. When the current batch updates finish, we [queue](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L203) another update to clear anything we might have collected in the meanwhile. However [before we update](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L328) we check if `hasChanges` is true.

Unfortunately the bug lies in that we [don't check](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L48-L510) reloads in `hasChanges`.

Some options for fixing:

- Check `self.reloadSections.count > 0` in `hasChanges`
  - Quickest fix
- Replace `batchUpdateOrReloadInProgress` with a "mode" enum to model states of `performBatchUpdates:completion:`:
  - Just before calling
  - Enter/exit update block
  - Enter/exit completion block
  - Finished (technically on completion block exit)

The latter is a more thorough solution and probably better in the long run given some of the plans I have for how batch operations are handled.

**Comment by jessesquires** [comment]
@rnystrom should we get this in 2.0 or release a 2.0.1 ?

**Comment by rnystrom** [comment]
@jessesquires let's do 2.0.1, pretty difficult/odd setup to get this to happen, and we've never seen it in IG, so I think we can take some time to do this one right.

**Comment by vldalx** [comment]
@rnystrom, Hi.
I've faced a crash. It looks like a reason for the crash the same as described above.

I'm trying to implement a chat using [IGListKit](https://github.com/Instagram/IGListKit). Messages should be grouped by date. My app fetches messages' batches from a server side while a user scrolls the chat.

So, I use `SectionController` as a messages' group.
If all new messages should be added into an existing group I add them to a `datasource `and invoke `collectionContext!.insert` method using `IndexSet`
If a new section or new sections should be added I add them to a `datasource `and invoke `adapter.performUpdates` method

Sometimes, if a user _scrolls very fast_ my app will crash.
There is a methods' calls flow:
1) `adapter.performUpdates` - the first messages' batch is loaded
2) a few `collectionContext!.insert` - a few batches are appended to the end of the first section
3) `adapter.performUpdates` - 3 new sections are added
4) `adapter.performUpdates` - a new messages' batch is appended to the end of the last section
5) `adapter.performUpdates` - a new messages' batch is appended to the end of the last section -> **CRASH**

My investigation shows, actually _4 step was not executed_. New cells were not inserted in UICollectionView. And on the 5 step I get a crash, because of I try insert a new bath, but UICollectionView doesn't about previously "added" batch.

If I invoke`adapter.performUpdates` method within **batch updating** everything works nice.

**Comment by rnystrom** [comment]
@vldalx that sounds like it might be a separate issue. I'd love if you could:

- File a new issue so we can track this
- Give some examples of your setup (e.g. your `IGListAdapterDataSource`, section controllers, and when/how the section controllers insert new messages)
- (_optional but extremely helpful_) An example project demoing the bug

Sounds like you might have found something really interesting!

**Comment by vldalx** [comment]
@rnystrom there was a mistake in my comment, sorry. I wrote the wrong methods' calls flow.
I have just fixed that.
Please, take a look at my comment one more time.
If you still need a separate issue, i'll create a new one.
