### ISSUE TITLE
Is there any kind of persistence support?

### ISSUE THREAD

**Issue by Ricardo1980** [Instagram/IGListKit#317]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

I downloaded and played with the sample code, and read docs about this library, but I don't see anything about persistence.
Evidently Instagram has it, because when I open it in airplane mode, I can see different cells.
Any doc or clue about persistence when using this library?
Thanks a lot.

**Comment by rnystrom** [comment]
@Ricardo1980 within Instagram we mostly just use `NSCoding` for everything. IGListKit doesn't have any part in persistence layers for data. Instead I'd recommend loading cached content from disk on startup, then replace it with network data when it comes in.

IGListKit makes this easy because you don't have to differentiate between cached and network content, and when data changes just call `adapter.performUpdates(animated: false)`.
