### ISSUE TITLE
How to return datasource count in section controller numberOfItems 

### ISSUE THREAD

**Issue by otymartin** [Instagram/IGListKit#341]
@rnystrom 

In my sectionController `numberOfItems`, I would like to return my `dataArray.count` as opposed to just `return 1` per sectionController. My dataArray.count varies as its populated by network queries.

The problem is my `dataArray` is in my `viewController` which is my datasource.

I can try to instantiate my `viewController` in my `sectionArray` and access the `dataArray.count` but problem I found is `numberOfItems` and I think the whole sectionController loads before my viewController's `viewDidLoad` method resulting in `nil` for my `dataArray.count`.

How can I fix this?

## New issue checklist

- [**TRUE**] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [**TRUE**] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information
- `IGListKit` version: 2.0
- iOS version(s): 9+
- CocoaPods/Carthage version: Latest
- Xcode version: 8
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

**Comment by rnystrom** [comment]
@otymartin instead of using the mutable `dataArray.count` in the section controller, I would use an immutable object that represents the data in your section. Whenever a network request finishes, you can call `performUpdates(...)` and recreate your immutable models.

Take a look at my [weather app data source](https://github.com/rnystrom/SimpleWeather/blob/master/SimpleWeather/Classes/ViewControllers/WeatherViewController.swift#L87-L114) as an example. Anytime something changes I recreate the models which power my different section controllers.

**Comment by otymartin** [comment]
Thanks @rnystrom Looks like I have to dive into a new topic `immutable models`. Thanks for providing your code, its helping alot.

**Comment by jessesquires** [comment]
🎉
