### ISSUE TITLE
Add -[IGListAdapter visibleCellsForObject:] API

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#437]
Got a request internally for this API. It's doable now, but more work than necessary:

- Get the section of an object with `sectionForObject:`
- Create an `NSIndexPath`
- Get the cell with `cellForRowAtIndexPath:`

Would be nice to just grab all visible cells that exist for a given object.

**Comment by Sherlouk** [comment]
@rnystrom 

In my attempts at wanting to learn a bit of ObjC I gave this a try, would you mind having a look at my implementation? Would really appreciate some feedback!

https://github.com/Sherlouk/IGListKit/commit/4f41c9e8d21e0d2f51a24e8b7a9e691c2fa332db

**Comment by PhilCai1993** [comment]
I have a question about the responsibility of `IGListAdapter`. 

Since it is totally data-driven, so all that I am concerned about is `SectionController` and the `Section` number. 

Is it really a good practise for adapter to retrieve `cell`? And will it be better if it's put in `IGListAdapter+View` or somewhere? And the same for `-[IGListAdapter sizeForItemAtIndexPath:]` and `-[IGListAdapter sizeForSupplementaryViewOfKind:atIndexPath:]`.

😳

**Comment by rnystrom** [comment]
@PhilCai1993 good question!

The cell APIs can be really useful for top-level (VC) systems that do things with the cells. E.g. on Instagram we have auto-playing-video cells. Instead of putting that work in the section controllers, we have an object that on each scroll tick searches the visible cells and plays the most visible. Check out #161 for more details.

Also the size methods are really really useful when using a custom layout (anything but `UICollectionViewFlowLayout`). #400 has some info on that setup. We also use this internally at Instagram.
