### ISSUE TITLE
Make Empty View move with Pull-to-Refresh

### ISSUE THREAD

**Issue by dshahidehpour** [Instagram/IGListKit#458]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### Current Situation

`IGListAdapter` has a delegate callback called, `emptyViewForListAdapter`, which allows users to configure a view that should appear when their `CollectionView` has no data. However, I've found that when the `CollectionView` also has a Refresh Control (available by default in iOS 10 and above), the experience isn't great.

![](https://media.giphy.com/media/d1E2l79fbBVbmS6k/giphy.gif)

### Fix Proposal 1: (Short-term solution)

Assuming this is something that community wants, we could modify IGListAdapter so that it takes whatever view is provided by the user, and simply put it inside a plain `UICollectionViewCell` whose size is that of the entire CV.

### Fix Proposal 2: (Less hacky, more work)

Introduce a new function `emptyCellForListAdapter:` or `emptyControllerForListAdapter:` which returns either a `UICollectionViewCell`, or a `IGSectionController` (respectively). The cell or section controller that is returned would be used to display something when the collection view is empty, thus making the empty view move when the Refresh Control is pulled.

This call would supercede `emptyViewForListAdapter` and it would be marked deprecated for future releases.

### Fix Proposal 3: (No Changes Necessary)
Simply create my own `IGSectionController` for empty states and wire it up to my own ListAdapter. I would simply choose to not use `emptyViewForListAdapter:`.

### Going Forward
Obviously there are a number of ways to tackle this, I'm really interested to see what the community thinks! This is what I'm going for:

![](https://media.giphy.com/media/l0ExnAQQ01R1m8IDu/giphy.gif)

### Questions
1. Should Empty View move with Pull-to-Refresh by default?
2. Is this behavior something that users would want to be able to turn on/off? (I imagine it would start as an `IGListExperiment` to start.
3. If there is no PTR, should the empty state view be able to move?

Looking forward to everyone's response!

**Comment by racer1988** [comment]
+1 for this.

In case of no data I am currently returning a specific NoDataSectionController and ignoring the emptyView method, exactly to resolve this issue

**Comment by rnystrom** [comment]
@dshahidehpour awesome write up here w/ examples. I'm absolutely down w/ this idea now. Let's do it!

We probably want to avoid adding a cell+section b/c that'll make translating index paths and collection view updates a nightmare. We could probably add the view right into the collection view maybe?

Do you want to take on this PR? Would be awesome.

**Comment by dshahidehpour** [comment]
@rnystrom I'm actually working on a pull request right now! I went the route of adding a section controller/cell. It wasn't painful at all, but, I might have done something horribly wrong. I'll put the PR up here so the community can see it, and if it's not what you want, I'll change it :)

**Comment by zhubofei** [comment]
@dshahidehpour I agree with @rnystrom Since the refresh view is not part of the data, it should not be a cell/section, which is binding to the data model. 

IMH, something like [UIRefreshControl](https://developer.apple.com/reference/uikit/uirefreshcontrol) in UITableView might be a better choice. 

Or something like [DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet) may be better for overall design 🤔? b/c unlike UITableView, collectionView does not restrict scroll direction. And pull-to-refresh is not suitable for horizontal scrolling.

**Comment by rnystrom** [comment]
@zhubofei small misunderstanding, I think. @dshahidehpour is going to change the empty view so it scrolls w/ the background. I don't think we're going to tough the PTR at all, esp since its built in w/ iOS 10 on `UICollectionView`.

I actually used the bg view b/c of exactly that sort of "empty view" design. But I think that scrolling w/ the PTR is a totally valid case, and its weird when the content doesn't scroll w/ the PTR.

**Comment by dshahidehpour** [comment]
UPDATE: Me trying to add a section controller was a terrible idea. I have a clean fix, just cleaning up. Expect to see a diff here soon :)

**Comment by dshahidehpour** [comment]
#462 BOOM

**Comment by dshahidehpour** [comment]
@racer1988 I just landed a fix for this in fce3286ae
