### ISSUE TITLE
Two questions about IGListSingleSectionController?

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#480]
1. Is it necessary to make `configureBlock` nonnull?
When initialize `IGListSingleSectionController`, a `configureBlock` is required to be nonnull.
But sometimes it's not required. For example, when `listAdapter:sectionControllerForObject:` is invoked to return a sectionController, if `object` is some special object, it is not necessary to config the sectionController using the `object`(such a static cell).

2. How about adding a `didSelectSingleSectionHandler` to be an alternative to `IGListSingleSectionControllerDelegate` since we have `configureBlock` and `sizeBlock`?
In this way, it's of benefit to write codes together. Of course it's not difficult to customize a `IGListBlockSupportedSingleSectionController` if needed.😄 
```
[[IGListSingleSectionController alloc] initWithCellClass:TipCell.class
        configureBlock:^(id item, UICollectionViewCell  *cell) {
// actually sometimes there's no need to do anything here
}
        sizeBlock:^CGSize(id item, id<IGListCollectionContext> collectionContext) {
          return CGSizeMake(DEVICE_WIDTH, TipCell.cellHeight);
        } actionHandler:^(id parameter){
          NSLog(@"select section");
         }];
```

**Comment by rnystrom** [comment]
@PhilCai1993 this would be a nice enhancement. No, the configure block should be `nullable`. 

I'm open to the selection change, making that a `nullable` block as well. We chose a delegate pattern so it would could be `nil`, but having `nil` parameters for the blocks should be fine I think!

The only concern w/ the selection part being a block is it will be prone to retain cycles, since I'd imagine consumers will access other state in that method.

For instance, if a view controller created the single section controller and did something like `[self presentViewController:...]` on selection, `self` will cause a cycle (assuming the VC owns the `IGListAdapter`).

Writing it out, I'm probably still opposed to changing that API.

**Comment by PhilCai1993** [comment]
And in `IGListSingleSectionControllerDelegate`:
  `- (void)didSelectSingleSectionController:(IGListSingleSectionController *)sectionController;` 
is it better to be `- (void)didSelectSingleSectionController:(IGListSingleSectionController *)sectionController object:(id)obj`?

For example: 

```
- (IGListSectionController<IGListSectionType> *)listAdapter:(IGListAdapter *)listAdapter
                                 sectionControllerForObject:(id)object {
 if ([object isKindOfClass:A.class]) {
IGListSingleSectionController *controller = [[IGListSingleSectionController alloc] initWith:ACellClass ...];
controller.delegate = self;
return controller;
} else if ([object isKindOfClass:B.class]) {
IGListSingleSectionController *controller = [[IGListSingleSectionController alloc] initWith:BCellClass ...];
controller.delegate = self;
return controller;
} 
}

//And In delegate

- (void)didSelectSingleSectionController:(IGListSingleSectionController *)sectionController {
I don't know what is the object, A/B?
}

//Then in this way

- (void)didSelectSingleSectionController:(IGListSingleSectionController *)sectionController object:(id)object {
I know  the "object"
}


```

**Comment by rnystrom** [comment]
@PhilCai1993 I like that! You could lookup the object using `-[IGListAdapter objectForSectionController:]`, but agreed providing the object makes it much simpler. PRs for each of these would be very appreciated!

**Comment by PhilCai1993** [comment]
Close #397
