### ISSUE TITLE
Should "invalidateLayoutForSectionController:" call "cellForItemAtIndex:" ?

### ISSUE THREAD

**Issue by diegorozen** [Instagram/IGListKit#511]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: commit 6bdcac
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

The latest API addition invalidateLayoutForSectionController: allows for a smooth animation of the cells, but cellForItemAtIndex: doesn't get call at the end of the animation. What should be the approach if I wanted to have a different cell layout/configuration for expanded vs collapsed state?

Thanks!

**Comment by rnystrom** [comment]
@diegorozen good question! I just ran into this yesterday on Instagram 😄 

What we do when the cell needs updated is call our configure methods again. Something like:

```objc
- (UICollectionViewCell *)cellForItemAtIndex:(NSInteger)index {
  MyCell *cell = // dequeue
  [cell configureWithData:self.data];
  return cell;
}

- (void)didSelectItemAtIndex:(NSInteger)index {
  [self.collectionContext invalidateLayoutForSectionController:self completion:nil];
  [self configureWithData:self.data];
}
```

Which works for us. I'd rather leave it to clients that need to reload data to do that manually since cells can be built to respond to changes in other ways, and I don't know think there's a good, single approach.

**Comment by jessesquires** [comment]
Sounds reasonable to me 👍

**Comment by diegorozen** [comment]
Works great, thanks!
