### ISSUE TITLE
why do not support iOS7？Our company order need to support iOS7？help

### ISSUE THREAD

**Issue by fanrong95** [Instagram/IGListKit#514]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by heumn** [comment]
I can only assume that like any other company, Instagram had to draw the line _somewhere_. Retorical question: why not support iOS 6 or even iOS 5 while you are at it? 😉 

Instagram for iOS requires iOS 8.

I would start the other way around and ask why would your company support iOS 7? Shouldnt you rather start pushing your boss that supporting iOS 7 is expensive and serves _very_ few people

Curent adpotion rate of iOS versions
https://mixpanel.com/trends/#report/ios_frag

![skjermbilde 2017-02-26 kl 14 39 35](https://cloud.githubusercontent.com/assets/1769314/23340139/768adf54-fc31-11e6-9933-95af36f3bc65.png)

**Comment by rnystrom** [comment]
@heumn is spot on. We dropped support late last year.

@fanrong95 the good news is making IGListKit iOS 7 compatible should be pretty simple. You could just fork the repo and re-apply [this commit](https://github.com/Instagram/IGListKit/commit/9e8ad9626ab91326b6bbb75cb6927f8dbe134896).

We're going to remove `IGListCollectionView` soon, so that'll make it even easier to drop in your own iOS-7-backfill collection view and not even have to fork the repo.
