### ISSUE TITLE
Any tips for section controller to know its "context"

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#596]
Sometimes in a SectionController, I need to get the index or some other "contextual" information about the `object` that configs the section controller.

For example, in a list of restaurants, each restaurant is an object that configs a section controller, naming `RestaurantSectionController`. Then in the `-didSelectItemAtIndex:`, maybe I need to know what's the index of the `restaurant` in the list (So I could tell the server the index of the restaurant in the list when clicking the restaurant). Or even more complex, the list is restaurants mixed with some other type of objects. As a result, if the `RestaurantSectionController` attempts to know what's the index of the `restaurant` in the list, or the index in the "restaurants", the `RestaurantSectionController` have to known the whole data that compose the list, which is kind of weird. 

I tried adding something like `IGListCollectionContext`, called `IGListDataContext`.

```ObjC
@protocol IGListDataContext <NSObject>

/**
 Returns a copy of all the objects currently powering the list, ordered.
 
 @return An array of objects.
 */
- (NSArray <id <IGListDiffable>> *)allSectionObjects;

@end

```
And let the adapter conform this protocol, and add a property to the `IGListSectionController`.

```ObjC
@interface IGListSectionController : NSObject

...

/**
 A context object for retriving objects that powering the list.
 */
@property (nonatomic, weak, nullable, readonly) id <IGListDataContext> dataContext;

...

@end
```

```ObjC
@implementation IGListAdapter

- (void)updateObjects:(NSArray *)objects dataSource:(id<IGListAdapterDataSource>)dataSource {
...

  for (id object in objects) {
       ...
        sectionController.collectionContext = self;
        sectionController.dataContext = self;
       ...
  }
...
}

#pragma mark - IGListDataContext

- (NSArray<id<IGListDiffable>> *)allSectionObjects {
    return self.objects; //self.sectionMap.objects;
}

@end
```

I don't know what's the better solution for this kind of situations, any tips?

By the way, will 3.0 be released recently? 

Thanks

**Comment by rnystrom** [comment]
@PhilCai1993 the goal is for section controllers not to have much knowledge about "global" scope. The most we really give in that sense is the `-[IGListCollectionContext sectionForSectionController:]` and `-[IGListSectionController isLastSection/isFirstSection]` APIs. That's all very much by design since we don't want to encourage "reaching over" to mess w/ other data or section controllers. If you're doing that sort of stuff it should probably happen up at the VC level.

However I know that these situations come up (and we have them in Instagram). The best approach we've seen is to create helper objects w/ locked-down APIs that you can share between section controllers.

```objc
@interface HelperObject : NSObject

- (id)initWithListAdapter:(IGListAdapter *)adapter;

- (NSArray *)allObjects;

@end

@implementation HelperObject {
  IGListAdapter *_adapter; // set ivar in init
}

- (NSArray *)allObjects {
  return _adapter.objects;
}

@end

@interface MyViewController : UIViewController <IGListAdapterDataSource> {
  HelperObject *_helper; // created when the adapter is created
}

- (IGListSectionController <IGListSectionType> *)listAdapter:(IGListAdapter *)listAdapter 
      sectionControllerForObject:(id)object {
    if (object == something) {
      return [[LabelSectionController alloc] initWithHelper:_helper];
    } else {
      return [[ImageSectionController alloc] initWithHelper:_helper];
    }
  }

@end
```

We use this type of pattern for all sorts of stuff. You'll create shareable objects and limit their APIs to be "readonly" so that section controllers aren't changing anything outside of their scope.

> By the way, will 3.0 be released recently?

"Soon" 😅

@jessesquires and I are putting the finishing pieces together and writing documentation. Shouldn't be long. We use `master` for Instagram though, so don't hesitate to point to that branch and start using features today!

**Comment by PhilCai1993** [comment]
😂 Why we are still using 2.1.0 today? Because IGListKit is updating so rapidly that I have to understand what are updated, to avoid misuse. 

Humm, do you have slack or whatever for communication for IGListKit?

**Comment by rnystrom** [comment]
> Humm, do you have slack or whatever for communication for IGListKit?

We don't yet. Though the project is scaling up, I like keeping all comms here so we can centralize/document everything. Might be nice as a way to discuss stuff like dates, urgent issues, etc.
