### ISSUE TITLE
3.0.0 Release

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#650]
Hi @rnystrom @jessesquires, 

When are planing to release new 3.0.0 version? I know master is stable but will be great if we can release new version more often. 

Thank you!

**Comment by Sherlouk** [comment]
Whilst I understand it's not helpful the only answer that's been given so far is "soon".

I understand Ryan and Jesse are finalising work and writing up the migration guides and other documentation and talks have already begun about the next major version.

Source:
- https://github.com/Instagram/IGListKit/issues/596#issuecomment-290546330
- https://github.com/Instagram/IGListKit/issues/633

Again whilst not ideal, and as you mentioned, `master` is stable and used by Instagram and other apps - so if you need/want the latest features then I recommend using that.

I'll leave the issue open for a member reply, especially since quite a few people are asking recently 😅

**Comment by rnystrom** [comment]
Very hard at work on it! Like @Sherlouk mentioned if you need features today `master` is totally fine (its what we use at Instagram).

3.0 has a lot of breaking changes in it so we're making sure to bundle as many big changes as possible to reduce churn on everyone.

**Comment by jessesquires** [comment]
@shuhrat10 - 3.0 is out now! 😄
