### ISSUE TITLE
Fix broken builds on travis-ci

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#668]
Not sure what the deal is because travis is pretty much always broken af.

Looks like XCTestExpectations are timing out.

Maybe we increase the timeout?

**Comment by Sherlouk** [comment]
To be fair the tests weren't working when I ran them locally yesterday (same tests)

Not convinced it's 100% to the fault of Travis.

**Comment by heshamsalman** [comment]
Same experience as @Sherlouk yesterday

**Comment by jessesquires** [comment]
lol. classic.

see, this is what happens when CI is totally unreliable.

**Comment by jessesquires** [comment]
also cc @rnystrom 

we should probably at least increase those timeouts to like `20`

**Comment by Sherlouk** [comment]
Is it worth giving something like Circle or Buddybuild a go? Had positive experiences with both of them in the past?

**Comment by heshamsalman** [comment]
@Sherlouk I've used both. My experience re: Travis v Circle is that Circle has about a third of the total time in CI and I found it to be more reliable. I hope y'all don't use the built in travis-cron feature, otherwise you're going to have to spin up a herokuapp that does it (it's what I did). 

BuddyBuild vs Travis: Similar to Circle in that it's much faster, but packed with features that are really more useful for a production app; not so much a framework. More expensive than Circle. Great for tracking down production crashes, _a la_ Fabric, but renders a video of the last few seconds before the crash and sends it your way.

**Comment by jessesquires** [comment]
we need free for OSS

**Comment by Sherlouk** [comment]
Circle & Buddybuild both have free packages for OSS projects

**Comment by rnystrom** [comment]
@jessesquires @Sherlouk there's a flaky test we have disabled internally that #657 fixes, but I don't think that has anything to do w/ the timeouts.

**Comment by jessesquires** [comment]
@rnystrom hm, yeah i'm getting a ton of failures and bullshit locally

**Comment by rnystrom** [comment]
@jessesquires which tests? The one I know about is

```
test_whenDeletingItemsTwice_withDataUpdatedTwice_thatAllUpdatesAppliedWithoutException
```

**Comment by jessesquires** [comment]
@rnystrom -- that one yes, but also see a ton of weirdness and/or flakiness

**Comment by tapanprakasht** [comment]
@rnystrom It looks like build issue is resolved. So I think this issue needs to be closed.
