### ISSUE TITLE
IGAssert and dedupe unique diffIdentifiers in IGListBindingSectionController

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#700]
Inspired by #696, we can't allow multiple view models with the same diff identifier inside `IGListBindingSectionController`. We should assert the same way we do in [IGListAdapter](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L541-L544) (but checking `diffIdentifier`s).

Maybe we move [this dedupe method](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L96-L110) to a helper function so that we can assert _and_ still handle the dupe case?

**Comment by weyert** [comment]
Isn't this issue covered by #821?

**Comment by weyert** [comment]
Does ticket still need work? @jessesquires @rnystrom ?

**Comment by rnystrom** [comment]
@weyert that PR doesn't address this. This issue is about asserting for unique view models within the binding SC itself.

**Comment by heumn** [comment]
best starter task

**Comment by weyert** [comment]
Oh, alright 👍

**Comment by weyert** [comment]
@rnystrom I have written the unit test and updated the code in the binding section controller only I need to copy-and-paste the `objectsWithDuplicateIdentifiersRemoved`-method to this file too. Otherwise I am getting a bunch of errors. Could you or someone else assist with ensuring I only have to use it once?
