### ISSUE TITLE
[Question] BSD License for dummies

### ISSUE THREAD

**Issue by HarshilShah** [Instagram/IGListKit#751]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

This is probably a stupid question, but I couldn’t find a reasonable answer anywhere so I thought I’d just ask anyway.

I’m working on a library of my own, and I wish to include IGListKit as a dependency within it. I will not be storing IGListKit within my library’s repository, and only linking to it as a dependency using the official Carthage and CocoaPods methods to do so.

So two questions about this:
- Do I need to include IGListKit's copyright notice within the library and/or any attached example projects?
- Does using IGListKit mean I have to use the same license or anything like that?

Again, I realise these are stupid questions, and I think I can guess the answers to both, but ones that I thought I’d get clarified regardless.

Thanks

**Comment by jessesquires** [comment]
Hey @HarshilShah ! 😄 

Not a stupid question at all. Software licensing is hard. In general, the [BSD license](https://opensource.org/licenses/BSD-3-Clause) is an extremely permissive license. (It's basically the MIT license, except it requires attribution and prevents endorsements.) Caveat — *I am not a lawyer*. 😉 

Despite some legal jargon, the 3 conditions are pretty straight-forward:

>1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 
----------

> Do I need to include IGListKit's copyright notice within the library and/or any attached example projects?

Yes (although this is rarely, if ever, enforced — generally speaking.)

> Does using IGListKit mean I have to use the same license or anything like that?

No. You're free to apply any license, or use this for closed-source project. 

--------------

I'd recommend using the MIT license for your library (assuming it will be open-source). This is probably the most common because it is the most permissive license.

**Comment by HarshilShah** [comment]
Thanks for the help @jessesquires! Definitely going ahead with MIT for my library.
