### ISSUE TITLE
 Embedded section controller always scroll horizontal direction

### ISSUE THREAD

**Issue by ajaybeniwal** [Instagram/IGListKit#806]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:3.0
- iOS version(s):11
- CocoaPods/Carthage version:
- Xcode version:8.3
- Devices/Simulators affected:Iphone7
- Reproducible in the demo project? (Yes/No):Yes
- Related issues:No

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
No Information
```
I am trying to make a UI like new IOS11 app store with help of IGLListKit , I am using Nested Horizontal collection view inside each section but the problem is that the embedded section controller always scroll horizontal direction, it is not following the line breaking mode of FlowLayout even if the height is there to draw second item vertically it still draws Horizontally. I have kept height in such a way that 3 items can fit vertically and remaining can come with horizontal scroll bars but it aligns all items at top and provides horizontal scrolling.
![screen shot 2017-06-14 at 4 40 59 pm](https://user-images.githubusercontent.com/658004/27127220-b71381a2-512c-11e7-9726-36cd05070539.png)
![img_2804](https://user-images.githubusercontent.com/658004/27127229-bf5a22f8-512c-11e7-9844-ce8a3566514f.JPG)

**Comment by rnystrom** [comment]
@ajaybeniwal so you're trying to get each section to flow vertically first, then expand to the right so you can swipe over to reveal another column of items, right?

- Are you using a nested `IGListAdapter` setup [like this example](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift)? Or is it just a plain `UICollectionView`?
- You're using `UICollectionViewFlowLayout`?

If using a nested adapter, this might require #752 since `UICollectionViewFlowLayout` puts all sections on the same "line".

However you might get away with just using a plain `UICollectionView` with each "page" being a section, and each vertical cell being an item.

**Comment by heumn** [comment]
Any update on this @ajaybeniwal ?
