### ISSUE TITLE
Live Data & IGList Grid by Type

### ISSUE THREAD

**Issue by thedevme** [Instagram/IGListKit#838]
![02f news - live game module - sm 2x](https://user-images.githubusercontent.com/1933678/27587764-9c42a380-5b13-11e7-886e-b9f7eb8e58c3.png)

I have been using IGList for about 6 months now and I have two questions:

1.  In the red section, I currently have the data in a separate model object called Game along with all of the other items called Video/Audio/Gallery etc.  I am looking for the best way to update just the Game object when live scoring is happening.  Suggestions?

2. In the orange section, I want to be able to have all gallery items next to each other in groups of two.  I was curious the best way to attack this in IGList.  Would this be more of a data manipulation or is there a more elegant way to implement this in IGList.

Thank you for any advice on these two topics

**Comment by thedevme** [comment]
Is there anyone that has any advice on this?

**Comment by rnystrom** [comment]
For #1, take a look at [this comment](https://github.com/Instagram/IGListKit/issues/832#issuecomment-312138965) about signal/delegate architectures and propagating events to section controllers.

For #2, IMO you should break those all up into separate section controllers:

- One for the image + text
- One for image + text-overlay
- And one for audio or w/e that is on the bottom

That way you can model your data into very specific pieces, and each of your section controllers should only have a single purpose/cell instead of getting to tangled. Hope this helps!
