### ISSUE TITLE
IGListAdapter‘s scrollViewDelegate

### ISSUE THREAD

**Issue by threeknife** [Instagram/IGListKit#842]
only 3 delegate was implemented.
- (void)scrollViewDidScroll:(UIScrollView *)scrollView
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate 

and other delegate like
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)scrollView
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView
was not implemented.

I want to know Why?

**Comment by rnystrom** [comment]
@threeknife simply necessity. Within Instagram these are the only methods that we have been using. It'll be simple to add these, but mostly leaning on the open source community to show a need, request, and fix + test. Tbh since we do not allow `@optional` in our protocols, this would have just added more unused boilerplate.

Def not opposed to adding if there's a real need in the future.
