### ISSUE TITLE
Section not getting refreshed on perromUpdates

### ISSUE THREAD

**Issue by iOSUser110** [Instagram/IGListKit#843]
One of my section data change after webservice success, so call performupdates on successs of webservice..but section not getting refreshed. why so ? any other solution
PLease reply asap

**Comment by rnystrom** [comment]
@iOSUser110 we're going to need a **lot** more information about your setup before diagnosing. Take a look at the [issue template](https://github.com/Instagram/IGListKit/blob/master/.github/ISSUE_TEMPLATE.md) for some idea of what we need. [Here](https://github.com/Instagram/IGListKit/issues/389) is a thread w/ some information that might be useful. Also since this probably has to do with models, make sure you read over the [diffing and isEqual guide](https://github.com/Instagram/IGListKit/blob/master/Guides/IGListDiffable%20and%20Equality.md).
