### ISSUE TITLE
How to surface the result of an async call back to a button or view within a cell?

### ISSUE THREAD

**Issue by chrismanderson** [Instagram/IGListKit#878]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

What's the recommended way of providing the end result of a async/networking call to a button or a view within a cell? 

Say I have a `Like` button on an Instagram post cell. I could setup a delegate from the cell to start the networking call. My question is, do you all have any recommendations on providing the result of that 'like' action back to the cell; e.g. if the "like" succeeded or failed. Another example is an 'Add to Cart' button. I could start a loading spinner on a button when I tap such a button; but I would need to provide the result back to the button when the call completes. I don't necessarily want to reload the entire cell after the networking call ends as I want to, for example, end a 'loading' spinner on the button gracefully versus a hard cell reload. 

I could setup the cell to be a delegate of the controller with some sort of `performedActionWasSuccessful(bool:)` call, but that feels sort of iffy to me. I've looked at some of the examples you all provide such as [RemoveCell](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/Views/RemoveCell.swift#L37) and I see a lot of great feedback about getting the tap action out of the cell using IGListKit, but not necessarily getting the result back into the cell. Thanks!

**Comment by rnystrom** [comment]
@chrismanderson great question! We could definitely provide a better example for this.

What we do is something like the following:

1. Do an async fetch in the section controller
2. In the callback (block or delegate, doesn't matter), ask the `[collectionContext cellForSectionController:atIndex:]` for the cell (on mobile but I think that's the API)
3. Configure the cell however you want. Be careful b/c it can be nil (in case you do something else with it)

Another option is to use some mutable state on the section controller that configures the cell in `cellForItemAtIndex:`. On your callback, change the local state (maybe `self.name = response["name"]`), then reload the section controller/cell. I personally like this approach because it keeps the cell configure code in one place vs spreading it out. But, it has the downside of animations (or can't do custom animations).

Plenty of options tho depending on your needs!

**Comment by chrismanderson** [comment]
Thanks for the response! That first option makes a lot of sense to me for my use case. The second seems a little iffier to me in terms of storing state on the VC, but always great to see options. It could be a great idea to add this into the example projects repo, maybe long with the `RemoveController` section; e.g. respond if the remove succeeds or fails.

**Comment by kanumuri9593** [comment]
hi @rnystrom @chrismanderson  ,Thank you its a nice option for my requirement too, but I have a general question extending this topic
lets say you are loading your posts similar to Instagram through some feed Objects array with each object goes into its own section controller and you are using lazy loading concept to keep increasing the array as shown in your examples, the the user clicked the Like and you configured your cell as you suggested
and cell is out of bounds like the user scrolled down/up;
Now my question is when user scrolls backs to the same cell what would be the behavior since we are using collection view the cells are reused so I thought the cell is build using the Post object from the initial array which doesn't contain the updated like status/count
should I reload the whole data ??
lets say since we are using lazy loading the Post like occurred in third batch of data now how will handle it??
would love your suggestion and expertise in handling this situation

**Comment by rnystrom** [comment]
@kanumuri9593 in Instagram we have mutable stores that track states like these. That's definitely what I would recommend. Here's an example in a GitHub app I'm building:

- Configure cell state in [cellForItemAtIndex:](https://github.com/rnystrom/Freetime/blob/8e39f2898867032089e618990ca09898981f8b7a/Classes/Notifications/NotificationSectionController.swift#L36)
- State is combination of [model || local store](https://github.com/rnystrom/Freetime/blob/8e39f2898867032089e618990ca09898981f8b7a/Classes/Notifications/NotificationSectionController.swift#L60)

**Comment by kanumuri9593** [comment]
@rnystrom Thanks for a quick response, I will look into your suggestions

**Comment by seanliu1** [comment]
> @kanumuri9593 in Instagram we have mutable stores that track states like these. That's definitely what I would recommend. Here's an example in a GitHub app I'm building:
> 
> * Configure cell state in [cellForItemAtIndex:](https://github.com/rnystrom/Freetime/blob/8e39f2898867032089e618990ca09898981f8b7a/Classes/Notifications/NotificationSectionController.swift#L36)
> * State is combination of [model || local store](https://github.com/rnystrom/Freetime/blob/8e39f2898867032089e618990ca09898981f8b7a/Classes/Notifications/NotificationSectionController.swift#L60)

@rnystrom how will you handle the case where one post is displayed in multiple cells, for this example [model || local state](https://github.com/GitHawkApp/GitHawk/blob/8e39f2898867032089e618990ca09898981f8b7a/Classes/Notifications/NotificationSectionController.swift#L60 ) state is updated only for one cell, and other visible cells does not know the state is changed.  The only solution I can come up is that we use announcer and listener pattern, then we can observe local state change.

**Comment by lorixx** [comment]
> how will you handle the case where one post is displayed in multiple cells, for this example model || local state state is updated only for one cell, and other visible cells do not know the state is changed. The only solution I can come up is that we use announcer and listener pattern, then we can observe local state change.

It seems like the problem is on where the source-of-truth is. If you dont want to listen to the local state change, then you just listen to the other model data source, and construct the view model for it. 

In RX world, this is referred to using the combineLatest for the data streams that you are interested in.

**Comment by seanliu1** [comment]
@lorixx Thanks for your reply. 
In that case, I assume section controller is responsible to listen for data source change, rebuild immutable viewmodel, then update current cell.  

I attached some code snippet, I would love to hear you feedback whether it is normal to go that route.

```
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
     return self.posts // an array of post id, no other properties since section controller will fetch it from cache
}

func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
      return PostSectionController(dataSource)
}

struct Post:ListDiffable {
  let postID:Int
}
struct PostViewModel {
    let name:String
    let imageURL:URL?
    let like:Int
   let comments:[String]
}

class PostSectionController:ListSectionController {
     let dataSource:DataProvider
     var viewModel:PostVIewModel?
    override func didUpdate(to object: Any) {
        guard let post = object as? Post else { return }
        viewModel = dataSource.object(for:post.id)
        dataSource.listen(post.id) { model in 
               // underlying model is changed (like, follow, comment etc)
               self.viewModel = viewModel
               collectionContext?.performBatch(animated: true, updates: { context in
                      context.reload(self)
              }
        }
        }
  }
```

**Comment by lorixx** [comment]
I think it's better not to use the SectionController to control/fetch the source of truth, it should be just handle the view model update and coordinate the events between cell and the section controller.

You should have a separate DataSource that implements the `ListAdapterDataSource` and keep the single source of truth for all the view models, which fetched from Cache in your example. Whenever your data source has update, you just inform the listAdapter to do -performUpdate.

It's not recommended to do 

```
collectionContext?.performBatch(animated: true, updates: { context in
                      context.reload(self)
              }
```
from section controller level.
