### ISSUE TITLE
Cells with wrong size

### ISSUE THREAD

**Issue by gbtt** [Instagram/IGListKit#883]
## New issue checklist

- [V ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [V ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.3.2
- CocoaPods/Carthage version: CocoaPods 1.1.1
- Xcode version: 8.3.3
- Devices/Simulators affected: iPhone 7 Plus, iOS Simulator
- Reproducible in the demo project? (Yes/No): 
- Related issues: 

Hi,
I have a cell (CityCell) showing an image and a label.
The first cell must have a length equal to the view, while the other cells must have half the length of the view.
So in the first row I have one item, in the other rows I have two items per row.

So I have this:

    override func sizeForItem(at index: Int) -> CGSize {
        let width = collectionContext!.containerSize.width
        if index == 0 {
            return CGSize(width: width, height: width/2)
        } else {
            return CGSize(width: width/2, height: width/2)
        }
    }

The problem is that the items have wrong size, and each time I scroll the view they assume different sizes.

I created a demo project with this problem: [link](https://github.com/gbtt/iglistkit-sizecellproblem)
and you can also see a video: [link](https://drive.google.com/open?id=0BxYN5UgjufTvT1dtVXZXN1VFekk)

I am currently solving this problem by creating another ViewCell that I use only for the first element. In cellForItem, if index == 0 I cast the first item to the new ViewCell otherwise to CityCell

Thanks... and a big thank you for this awesome framework

**Comment by weyert** [comment]
Your code in your repo is empty. Could you submit the code?

**Comment by gbtt** [comment]
oops :)
I have submitted the code.

**Comment by heumn** [comment]
Hey, thanks for providing a demo project, that makes it easier to help :)

The problem seems to be that you are hard coding the frames of the labels 

![skjermbilde 2017-08-25 kl 00 10 09](https://user-images.githubusercontent.com/1769314/29691114-1aa7c298-892a-11e7-9bf5-6e2b2bce5ed5.png)

It won't help what frame you set as the superview, when the image and the label has hard coded sizes.

I would propose you watch some of the great WWDC videos about AutoLayout. It will help you a lot with understanding how the layout engine of UIKit works.

To fix your problem I added an extension to UIView that will fill the view with the subview.

![skjermbilde 2017-08-25 kl 00 12 15](https://user-images.githubusercontent.com/1769314/29691153-4fdd4dd4-892a-11e7-8c69-c51dba7c6e98.png)

![skjermbilde 2017-08-25 kl 00 12 02](https://user-images.githubusercontent.com/1769314/29691157-5402de60-892a-11e7-9242-0b0cd7fe5451.png)

You can grab it here if you want to re-use it:

```
extension UIView {

    func fillWith(_ view: UIView, usingConstraints: Bool = true) {
        addSubview(view)
        if usingConstraints {
            view.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                topAnchor.constraint(equalTo: view.topAnchor),
                leftAnchor.constraint(equalTo: view.leftAnchor),
                rightAnchor.constraint(equalTo: view.rightAnchor),
                bottomAnchor.constraint(equalTo: view.bottomAnchor),
            ])
        } else {
            view.frame = bounds
            view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        }
    }
}
```

**Comment by rnystrom** [comment]
@heumn slay!

**Comment by weyert** [comment]
Totally forgot to look into this. My apologies 😞

**Comment by gbtt** [comment]
Hi @heumn 
thanks for the information and for the fix! :)

**Comment by heumn** [comment]
My pleasure :) Best of luck!
