### ISSUE TITLE
Is it possible to make a spreadsheet?

### ISSUE THREAD

**Issue by aelam** [Instagram/IGListKit#896]
## New issue checklist
The main features in my mind are 
* supports multi-sticky-headers
* supports Sticky one~three first columns in each row 
* supports h scroll when each row has same offSetX when sheet is scrolling
* easy to configure section-row-column data
* easy to configure cellClass or cellNib for each column, same in columns of header 

The Layout Class seems not support these, I'm thinking embed a collectionView in each row for columns. 
How is the possibility to make a great spreadsheet by this 

- [ TRUE] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ TRUE] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
Wo boy, this would be awesome to see in practice. *For sure* you will need a custom layout beyond what `UICollectionViewFlowLayout` and `IGListCollectionViewLayout` provide.

As far as "can IGListKit" do it? I'm almost certain that it can. IGListKit is almost entirely a data source framework, there is very little that we do with the UI as far as how things appear (our custom layout is about it).

@aelam I'm going to close this, since there doesn't seem to be anything that the IGListKit team can action. If you do get this working it'd be an amazing tech demo that I'd be happy to help show off/promote!
