### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#925]
I honestly have 0 experience with the SPM. I'd love for IGListKit to be available via all possible package managers.

- Is this even feasible since its an ObjC library?
- What all is required?
- Is SPM widely used?

cc @jessesquires for help 😇

**Comment by jessesquires** [comment]
SPM supports building C, C++, ObjC packages but doesn't support iOS/macOS at all. I mean, we should be able to get everything building via SPM (especially since there are no xibs, etc.), but there's no Xcode integration or anything like that so it's pretty pointless.

Only real use-case right now is on linux/server.

**Comment by rnystrom** [comment]
> Only real use-case right now is on linux/server.

Welp, move along then.

**Comment by jessesquires** [comment]
LOL

we could leave this open as an FYI / future work

**Comment by rocklyve** [comment]
with [Accio](https://github.com/JamitLabs/Accio) you are able to use SwiftPM on iOS.
Support would be very nice now!

**Comment by rocklyve** [comment]
Support added with https://github.com/Instagram/IGListKit/commit/7551573c9db666d4dfadbb6f89b4ca3e2dfd0c60
