### ISSUE TITLE
Pager layout with dynamic cell height 

### ISSUE THREAD

**Issue by tunidev** [Instagram/IGListKit#973]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### Question

Please help me figuring out how to use IGListKit to create this layout : 

<img width="699" alt="layout" src="https://user-images.githubusercontent.com/4885143/31766104-f0bdabf0-b4c6-11e7-841c-42302e67c4ca.png">

- User can scroll horizontally to change pages.
- Pages has dynamic height that can be higher than the screen height.
- User can scroll vertically to see the full content of pages.
- Pagination system (like pagination enabled in `scrollView`).

**Comment by rnystrom** [comment]
@tunidev you'll want to use a custom `UICollectionViewLayout` in order to do this. IGListKit will work just fine for this, but we don't provide any layouts that do this.

The horizontal+vertical scrolling might make it a little complicated too. You could possible use a horizontal scroll `IGListAdapter` and put a `UIScrollView` inside each cell?

However I'm going to close this out since its beyond the scope of what IGListKit provides and is more specific to your design. Feel free to keep brainstorming though!
