### ISSUE TITLE
Example of your latest addition

### ISSUE THREAD

**Issue by weyert** [Instagram/IGListKit#974]
@rnystrom I noticed that you have added listening functionality to `IGListKit` in your latest commit and got curious.  I was wondering what the use case would be. For example, how or when would you use this? 

Let me ask it differently, would you ever use it in `GitHawk` and why?

**Comment by rnystrom** [comment]
I’ll add a bit more explanation later, but this was an internal feature request. We have a lot of stuff that triggers after content finishes updating

So instead of adding tons of lines to the completion block in every view controller, we can compose a bunch of objects that listen to this event and do work.

Lets us reuse more code, less boilerplate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
